---
## Here, helm keep track of what dependencies that are required for the application. Dependencies should be listed here,
## then the dependencies updated with:
##
##    helm dep update
##
## and the requirements.lock file commited.
##
 dependencies:
   - name: "kubernetes-ingress"
     version: "0.7.0"
     repository: "https://haproxytech.github.io/helm-charts"
     condition: haproxy.enabled
     alias: "haproxy"
