{{- range $config := .Values.configFiles }}
{{- if $config.create }}
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    heritage: "{{ $.Release.Service }}"
    release: "{{ $.Release.Name }}"
  name: {{ regexReplaceAll "[.]" $config.name "-" }}
data:
  {{ $config.key | default $config.name }}: |
{{ tpl $config.data $ | indent 6 }}
---
{{- end }}
{{- end }}