{{- range $config := .Values.configs }}
{{- if $config.create }}
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    heritage: "{{ $.Release.Service }}"
    release: "{{ $.Release.Name }}"
  name: {{ $config.name }}
data:
  {{- range $item := $config.data }}
  {{ $item.subPath}}: |
{{ $item.content | indent 6 }}
  {{- end }}
{{- end }}
---
{{- end }}

