apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "dockermailserver.fullname" . }}-secrets
data:
{{- range $path, $content := .Files.Glob  "config/**" }}
  {{- /* Process files that contains public or private or secret in their name */}}  
  {{- if or (contains "private" $path) (contains "public" $path) (contains ".secret" $path) }}
  {{ $path | replace "/" "." }}: {{ tpl ($.Files.Get $path) $ | b64enc }}
  {{- end }}
{{ end }}