{{- range $secret := .Values.secrets }}
{{- if $secret.create }}
apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    heritage: "{{ $.Release.Service }}"
    release: "{{ $.Release.Name }}"
  name: {{ $secret.name }}
data:
  {{- range $item := $secret.data }}
  {{ $item.subPath}}: |
{{ $item.content | indent 6 }}
  {{- end }}
{{- end }}
---
{{- end }}

